//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalTeste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Questionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tab_Questionario()
        {
            this.Tab_QuestionarioLetras = new HashSet<Tab_QuestionarioLetras>();
        }
    
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public int Acertos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_QuestionarioLetras> Tab_QuestionarioLetras { get; set; }
        public virtual TAB_Usuario TAB_Usuario { get; set; }
    }
}
